graph TD
commit_d2427ec -->|README.rst| commit_d2427ec_files
commit_bb45778 -->|requests/core.py| commit_bb45778_files
commit_18db8b8 -->|requests/__init__.py| commit_18db8b8_files
commit_8fd480d -->|README.rst| commit_8fd480d_files
commit_d6e7e19 -->|HISTORY.rst| commit_d6e7e19_files
commit_7ed73b2 -->|.gitignore| commit_7ed73b2_files
commit_a42c003 -->|README.rst| commit_a42c003_files
commit_1b88561 -->|README.rst| commit_1b88561_files
commit_7b65838 -->|README.rst| commit_7b65838_files
commit_c9b0f8f -->|README.rst| commit_c9b0f8f_files
commit_d4db03d -->|README.rst| commit_d4db03d_files
commit_52de0ba -->|README.rst| commit_52de0ba_files
commit_bb56142 -->|README.rst| commit_bb56142_files
commit_908d7de -->|README.rst| commit_908d7de_files
commit_4a3bee6 -->|README.rst| commit_4a3bee6_files
commit_8cca789 -->|README.rst| commit_8cca789_files
commit_88b64d2 -->|README.rst| commit_88b64d2_files
commit_a2ecf9c -->|README.rst| commit_a2ecf9c_files
commit_d789bad -->|README.rst| commit_d789bad_files
commit_00d900c -->|README.rst| commit_00d900c_files
commit_927294f -->|README.rst| commit_927294f_files
commit_2b54b01 -->|README.rst| commit_2b54b01_files
commit_71626de -->|README.rst| commit_71626de_files
commit_839873c -->|docs/MANIFEST.in| commit_839873c_files
commit_2cc8015 -->|README.rst| commit_2cc8015_files
commit_98d257e -->|HISTORY.rst| commit_98d257e_files
commit_090fcf1 -->|TODO.rst| commit_090fcf1_files
commit_e76fa91 -->|docs/Makefile<br/>docs/conf.py<br/>docs/index.rst<br/>docs/make.bat| commit_e76fa91_files
commit_4a3f559 -->|test_requests.py| commit_4a3f559_files
commit_fdd54e1 -->|requests/core.py| commit_fdd54e1_files
commit_9f4ce17 -->|setup.py| commit_9f4ce17_files
commit_e403a8a -->|requests/core.py| commit_e403a8a_files
commit_e796aae -->|requests/core.py| commit_e796aae_files
commit_4018276 -->|requests/core.py| commit_4018276_files
commit_2c168d2 -->|reqs.txt| commit_2c168d2_files
commit_59c6aeb -->|requests/core.py| commit_59c6aeb_files
commit_f566bb2 -->|requests/core.py| commit_f566bb2_files
commit_f1d9aae -->|requests/core.py| commit_f1d9aae_files
commit_7de5726 -->|TODO.rst| commit_7de5726_files
commit_6fb1997 -->|requests/core.py| commit_6fb1997_files
commit_3c32045 -->|requests/core.py| commit_3c32045_files
commit_71df02d -->|requests/core.py| commit_71df02d_files
commit_871de2a -->|requests/core.py| commit_871de2a_files
commit_4f9d598 -->|requests/core.py| commit_4f9d598_files
commit_327d923 -->|requests/core.py| commit_327d923_files
commit_44aa680 -->|requests/core.py| commit_44aa680_files
commit_d4c1ecc -->|README.rst| commit_d4c1ecc_files
commit_e9c2b91 -->|requests/core.py| commit_e9c2b91_files
commit_af272d5 -->|requests/core.py| commit_af272d5_files
commit_49f915f -->|test_requests.py| commit_49f915f_files
commit_32cc197 -->|requests/core.py| commit_32cc197_files
commit_ef9bae8 -->|requests/core.py| commit_ef9bae8_files
commit_54240b4 -->|requests/core.py| commit_54240b4_files
commit_b72e1d1 -->|requests/core.py| commit_b72e1d1_files
commit_d8b1957 -->|requests/core.py| commit_d8b1957_files
commit_d6cf93e -->|README.rst| commit_d6cf93e_files
commit_c840bc7 -->|README.rst| commit_c840bc7_files
commit_b079a4e -->|README.rst| commit_b079a4e_files
commit_2384286 -->|README.rst| commit_2384286_files
commit_45c6897 -->|README.rst| commit_45c6897_files
commit_a6ffd97 -->|README.rst| commit_a6ffd97_files
commit_853a4fd -->|reqs.txt<br/>requests/__init__.py<br/>requests/core.py| commit_853a4fd_files
commit_ffdbc38 -->|.gitignore| commit_ffdbc38_files
commit_72e99c0 -->|HISTORY.rst| commit_72e99c0_files
commit_c51b44d -->|LICENSE| commit_c51b44d_files
commit_75b499d -->|test_requests.py| commit_75b499d_files
commit_0477018 -->|setup.py| commit_0477018_files
commit_d0bf553 -->|README| commit_d0bf553_files
commit_e7615cb -->|README| commit_e7615cb_files